image: gitlab/dind

stages:
  - build
  - deploy

variables:
  REPOSITORY_URL: jalcalaroot
  dc_image_name : ansible1
  dc_username : "$dc_username"
  dc_password : "$dc_password"
build:
  stage: build
  script:
  - docker login -u "$dc_username" -p "$dc_password"
  - docker build -t "$dc_image_name" .
  - docker tag "$dc_image_name" "$REPOSITORY_URL/$dc_image_name"
  - docker push "$REPOSITORY_URL/$dc_image_name"
  
deploy:
  stage: deploy
  environment: dev
  script:
    - apt-get update -y && apt-get install sshpass openssh-server -y
    - service ssh start
    - update-rc.d ssh defaults
    - mkdir -p ~/.ssh
    - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh "$user"@"$dev" && echo "hola" >> /root/hola.txt
    - df -h