image: gitlab/dind
variables:
  REPOSITORY_URL: jalcalaroot
  dc_image_name : ansible1
  dc_username : "$dc_username"
  dc_password : "$dc_password"
services:
  - docker:dind
before_script:
    - docker login -u "$dc_username" -p "$dc_password"
    - apt-get update -qq && apt-get install -y -qq ssh sshpass
build:
  stage: build
  script:
    - docker build -t "$dc_image_name" .
    - docker tag "$dc_image_name" "$REPOSITORY_URL/$dc_image_name"
    - docker push "$REPOSITORY_URL/$dc_image_name"


    