deploy-to-swarm:
  stage: deploy
  image: docker:latest
  script:
  - docker login -u "$dc_username" -p "$dc_password"
  - docker build -t "$dc_image_name" .
  - docker tag "$dc_image_name" "$REPOSITORY_URL/$dc_image_name"
  - docker push "$REPOSITORY_URL/$dc_image_name"
  environment:
    name: master
    url: tcp://116.203.157.99:2377
  only:
    - master

