image: docker:latest
variables:
  REPOSITORY_URL: https://hub.docker.com/
  dc_image_name : ansible1
  dc_username: jalcalaroot
  dc_password: admin19226543
services:
  - docker:dind
before_script:
    - docker login -u "$dc_username" -p "$dc_password"
build-master:
  stage: build
  script:
    - docker build -t "$dc_image_name" .
    - docker tag "$dc_image_name" "$REPOSITORY_URL/$dc_image_name"
    
    - docker push "$REPOSITORY_URL/$dc_image_name"
  only:
    - master