variables:
  REPOSITORY_URL: jalcalaroot
  dc_image_name : ansible1
  dc_username : "$dc_username"
  dc_password : "$dc_password"
before_script:
    - docker login -u "$dc_username" -p "$dc_password"
build:
  stage: build
  image: gitlab/dind:latest
  script:
    - docker build -t "$dc_image_name" .
    - docker tag "$dc_image_name" "$REPOSITORY_URL/$dc_image_name"
    - docker push "$REPOSITORY_URL/$dc_image_name"
deploy:
  stage: deploy
  image: ubuntu:latest
  only:
    - "master"
  environment: production
  services:
    - docker:dind
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install sudo openssh-server sshpass python vim nano wget curl htop zip perl aptitude -y 
  script:
   - sshpass -p "$password" root@159.69.187.77
    